# -*- coding: utf-8 -*-
"""numpy1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r7_VWZnV1tAkkKSQGzjjZ7s5fg9-LuN9
"""

import numpy

arr=numpy.array([1,2,3])
print(arr)
print(type(arr))

"""# for comment

"""

l=[1,2,3, 'python']
print(l)
print(type(l))

arr=numpy.array([[1,2,3, 'python']])
print(arr)
print(type(arr))

arr=numpy.array([])
print(arr)
print(type(arr))

l = []
print(l)
print(type(l))

"""Types of Array:
1D
2D
N dimensional



To find the dimension we use size (no of elements)
 array_name.ndim
 array_name.size
"""

arr=numpy.array([1, 2, 3])
print(arr)
print(type(arr))
print("size=",arr.size)
print("shape=",arr.shape)

print(arr.ndim)

a = numpy.array([ [1,2,3] ])
print( a.ndim )
print(a)
print("size=",a.size)
print("shape=",a.shape)

a = numpy.array([ [1,2,3], [4,5,6]])
print( a.ndim )
print(a)
print("size=",a.size)
print("shape=",a.shape)